instruct generation
tag_evol_tag3_7b_yxprompt
INFO 03-29 14:25:50 __init__.py:207] Automatically detected platform cuda.
WARNING 03-29 14:25:50 config.py:2448] Casting torch.bfloat16 to torch.float16.
INFO 03-29 14:25:58 config.py:549] This model supports multiple tasks: {'reward', 'score', 'embed', 'classify', 'generate'}. Defaulting to 'generate'.
INFO 03-29 14:25:58 config.py:1382] Defaulting to use mp for distributed inference
INFO 03-29 14:25:58 llm_engine.py:234] Initializing a V0 LLM engine (v0.7.3) with config: model='/home/share/models/Qwen2.5-72B-Instruct', speculative_config=None, tokenizer='/home/share/models/Qwen2.5-72B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/home/share/models/Qwen2.5-72B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"max_capture_size":256}, use_cached_outputs=False, 
WARNING 03-29 14:25:59 multiproc_worker_utils.py:300] Reducing Torch parallelism from 16 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
INFO 03-29 14:25:59 custom_cache_manager.py:19] Setting Triton cache manager to: vllm.triton_utils.custom_cache_manager:CustomCacheManager
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:25:59 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:25:59 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:25:59 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:25:59 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:25:59 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:25:59 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:25:59 multiproc_worker_utils.py:229] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:26:01 cuda.py:178] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:26:01 cuda.py:226] Using XFormers backend.
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:26:01 cuda.py:178] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:26:01 cuda.py:226] Using XFormers backend.
INFO 03-29 14:26:01 cuda.py:178] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 03-29 14:26:01 cuda.py:226] Using XFormers backend.
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:26:01 cuda.py:178] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:26:01 cuda.py:226] Using XFormers backend.
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:26:01 cuda.py:178] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:26:01 cuda.py:226] Using XFormers backend.
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:26:01 cuda.py:178] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:26:01 cuda.py:226] Using XFormers backend.
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:26:01 cuda.py:178] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:26:01 cuda.py:226] Using XFormers backend.
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:26:01 cuda.py:178] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:26:01 cuda.py:226] Using XFormers backend.
INFO 03-29 14:26:03 utils.py:916] Found nccl from library libnccl.so.2
INFO 03-29 14:26:03 pynccl.py:69] vLLM is using nccl==2.21.5
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:26:03 utils.py:916] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:26:03 utils.py:916] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:26:03 pynccl.py:69] vLLM is using nccl==2.21.5
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:26:03 pynccl.py:69] vLLM is using nccl==2.21.5
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:26:03 utils.py:916] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:26:03 pynccl.py:69] vLLM is using nccl==2.21.5
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:26:03 utils.py:916] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:26:03 pynccl.py:69] vLLM is using nccl==2.21.5
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:26:03 utils.py:916] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:26:03 utils.py:916] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:26:03 utils.py:916] Found nccl from library libnccl.so.2
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:26:03 pynccl.py:69] vLLM is using nccl==2.21.5
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:26:03 pynccl.py:69] vLLM is using nccl==2.21.5
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:26:03 pynccl.py:69] vLLM is using nccl==2.21.5
WARNING 03-29 14:26:04 custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=2892662)[0;0m WARNING 03-29 14:26:04 custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=2892661)[0;0m WARNING 03-29 14:26:04 custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=2892660)[0;0m WARNING 03-29 14:26:04 custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=2892659)[0;0m WARNING 03-29 14:26:04 custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=2892663)[0;0m WARNING 03-29 14:26:04 custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=2892664)[0;0m WARNING 03-29 14:26:04 custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[1;36m(VllmWorkerProcess pid=2892658)[0;0m WARNING 03-29 14:26:04 custom_all_reduce.py:136] Custom allreduce is disabled because it's not supported on more than two PCIe-only GPUs. To silence this warning, specify disable_custom_all_reduce=True explicitly.
INFO 03-29 14:26:04 shm_broadcast.py:258] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1, 2, 3, 4, 5, 6, 7], buffer_handle=(7, 4194304, 6, 'psm_c2549182'), local_subscribe_port=37837, remote_subscribe_port=None)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:26:04 model_runner.py:1110] Starting to load model /home/share/models/Qwen2.5-72B-Instruct...
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:26:04 model_runner.py:1110] Starting to load model /home/share/models/Qwen2.5-72B-Instruct...
INFO 03-29 14:26:04 model_runner.py:1110] Starting to load model /home/share/models/Qwen2.5-72B-Instruct...
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:26:04 model_runner.py:1110] Starting to load model /home/share/models/Qwen2.5-72B-Instruct...
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:26:04 model_runner.py:1110] Starting to load model /home/share/models/Qwen2.5-72B-Instruct...
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:26:04 model_runner.py:1110] Starting to load model /home/share/models/Qwen2.5-72B-Instruct...
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:26:04 model_runner.py:1110] Starting to load model /home/share/models/Qwen2.5-72B-Instruct...
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:26:04 model_runner.py:1110] Starting to load model /home/share/models/Qwen2.5-72B-Instruct...
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:30:09 model_runner.py:1115] Loading model weights took 16.9989 GB
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:30:09 model_runner.py:1115] Loading model weights took 16.9989 GB
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:30:09 model_runner.py:1115] Loading model weights took 16.9989 GB
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:30:09 model_runner.py:1115] Loading model weights took 16.9989 GB
INFO 03-29 14:30:09 model_runner.py:1115] Loading model weights took 16.9989 GB
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:30:09 model_runner.py:1115] Loading model weights took 16.9989 GB
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:30:09 model_runner.py:1115] Loading model weights took 16.9989 GB
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:30:09 model_runner.py:1115] Loading model weights took 16.9989 GB
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:32:13 worker.py:267] Memory profiling takes 122.93 seconds
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:32:13 worker.py:267] the current vLLM instance can use total_gpu_memory (31.74GiB) x gpu_memory_utilization (0.95) = 30.15GiB
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:32:13 worker.py:267] model weights take 17.00GiB; non_torch_memory takes 0.24GiB; PyTorch activation peak memory takes 3.19GiB; the rest of the memory reserved for KV Cache is 9.73GiB.
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:32:13 worker.py:267] Memory profiling takes 123.01 seconds
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:32:13 worker.py:267] the current vLLM instance can use total_gpu_memory (31.74GiB) x gpu_memory_utilization (0.95) = 30.15GiB
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:32:13 worker.py:267] model weights take 17.00GiB; non_torch_memory takes 0.20GiB; PyTorch activation peak memory takes 3.19GiB; the rest of the memory reserved for KV Cache is 9.77GiB.
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:32:13 worker.py:267] Memory profiling takes 122.93 seconds
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:32:13 worker.py:267] the current vLLM instance can use total_gpu_memory (31.74GiB) x gpu_memory_utilization (0.95) = 30.15GiB
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:32:13 worker.py:267] model weights take 17.00GiB; non_torch_memory takes 0.19GiB; PyTorch activation peak memory takes 3.19GiB; the rest of the memory reserved for KV Cache is 9.78GiB.
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:32:13 worker.py:267] Memory profiling takes 123.06 seconds
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:32:13 worker.py:267] the current vLLM instance can use total_gpu_memory (31.74GiB) x gpu_memory_utilization (0.95) = 30.15GiB
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:32:13 worker.py:267] model weights take 17.00GiB; non_torch_memory takes 0.24GiB; PyTorch activation peak memory takes 3.19GiB; the rest of the memory reserved for KV Cache is 9.73GiB.
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:32:13 worker.py:267] Memory profiling takes 123.04 seconds
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:32:13 worker.py:267] the current vLLM instance can use total_gpu_memory (31.74GiB) x gpu_memory_utilization (0.95) = 30.15GiB
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:32:13 worker.py:267] model weights take 17.00GiB; non_torch_memory takes 0.24GiB; PyTorch activation peak memory takes 3.19GiB; the rest of the memory reserved for KV Cache is 9.73GiB.
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:32:13 worker.py:267] Memory profiling takes 123.04 seconds
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:32:13 worker.py:267] the current vLLM instance can use total_gpu_memory (31.74GiB) x gpu_memory_utilization (0.95) = 30.15GiB
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:32:13 worker.py:267] model weights take 17.00GiB; non_torch_memory takes 0.24GiB; PyTorch activation peak memory takes 3.19GiB; the rest of the memory reserved for KV Cache is 9.73GiB.
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:32:13 worker.py:267] Memory profiling takes 123.02 seconds
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:32:13 worker.py:267] the current vLLM instance can use total_gpu_memory (31.74GiB) x gpu_memory_utilization (0.95) = 30.15GiB
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:32:13 worker.py:267] model weights take 17.00GiB; non_torch_memory takes 0.19GiB; PyTorch activation peak memory takes 3.19GiB; the rest of the memory reserved for KV Cache is 9.78GiB.
INFO 03-29 14:32:13 worker.py:267] Memory profiling takes 123.32 seconds
INFO 03-29 14:32:13 worker.py:267] the current vLLM instance can use total_gpu_memory (31.74GiB) x gpu_memory_utilization (0.95) = 30.15GiB
INFO 03-29 14:32:13 worker.py:267] model weights take 17.00GiB; non_torch_memory takes 0.25GiB; PyTorch activation peak memory takes 3.19GiB; the rest of the memory reserved for KV Cache is 9.72GiB.
INFO 03-29 14:32:13 executor_base.py:111] # cuda blocks: 15918, # CPU blocks: 6553
INFO 03-29 14:32:13 executor_base.py:116] Maximum concurrency for 32768 tokens per request: 7.77x
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:32:26 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:32:26 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:32:26 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:32:27 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:32:28 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:32:28 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 03-29 14:32:28 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:32:28 model_runner.py:1434] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
[1;36m(VllmWorkerProcess pid=2892661)[0;0m INFO 03-29 14:33:30 model_runner.py:1562] Graph capturing finished in 64 secs, took 3.03 GiB
INFO 03-29 14:33:30 model_runner.py:1562] Graph capturing finished in 62 secs, took 3.04 GiB
[1;36m(VllmWorkerProcess pid=2892660)[0;0m INFO 03-29 14:33:30 model_runner.py:1562] Graph capturing finished in 64 secs, took 3.04 GiB
[1;36m(VllmWorkerProcess pid=2892658)[0;0m INFO 03-29 14:33:30 model_runner.py:1562] Graph capturing finished in 64 secs, took 3.03 GiB
[1;36m(VllmWorkerProcess pid=2892659)[0;0m INFO 03-29 14:33:30 model_runner.py:1562] Graph capturing finished in 62 secs, took 3.04 GiB
[1;36m(VllmWorkerProcess pid=2892663)[0;0m INFO 03-29 14:33:30 model_runner.py:1562] Graph capturing finished in 63 secs, took 3.03 GiB
[1;36m(VllmWorkerProcess pid=2892664)[0;0m INFO 03-29 14:33:30 model_runner.py:1562] Graph capturing finished in 63 secs, took 3.03 GiB
[1;36m(VllmWorkerProcess pid=2892662)[0;0m INFO 03-29 14:33:30 model_runner.py:1562] Graph capturing finished in 63 secs, took 3.03 GiB
INFO 03-29 14:33:30 llm_engine.py:436] init engine (profile, create kv cache, warmup model) took 200.89 seconds
./datas/databricks-dolly-15k/databricks-dolly-15k.json.cgtag_datas.json not exsits
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop.
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Traceback (most recent call last):
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/utils.py", line 2196, in run_method
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 91, in start_worker_execution_loop
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.execute_model(execute_model_req=None)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 420, in execute_model
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.model_runner.execute_model(
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1724, in execute_model
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_or_intermediate_states = model_executable(
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 486, in forward
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/compilation/decorators.py", line 172, in __call__
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self.forward(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 348, in forward
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states, residual = layer(
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 247, in forward
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.self_attn(
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 180, in forward
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output, _ = self.o_proj(attn_output)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 1149, in forward
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output_parallel = self.quant_method.apply(self,
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 142, in apply
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return F.linear(x, layer.weight, bias)
[1;36m(VllmWorkerProcess pid=2892663)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.00 MiB. GPU 6 has a total capacity of 31.74 GiB of which 173.12 MiB is free. Including non-PyTorch memory, this process has 31.56 GiB memory in use. Of the allocated memory 27.90 GiB is allocated by PyTorch, with 48.00 MiB allocated in private pools (e.g., CUDA Graphs), and 154.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop.
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Traceback (most recent call last):
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/utils.py", line 2196, in run_method
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 91, in start_worker_execution_loop
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.execute_model(execute_model_req=None)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 420, in execute_model
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.model_runner.execute_model(
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1724, in execute_model
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_or_intermediate_states = model_executable(
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 486, in forward
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/compilation/decorators.py", line 172, in __call__
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self.forward(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 348, in forward
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states, residual = layer(
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 247, in forward
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.self_attn(
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 180, in forward
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output, _ = self.o_proj(attn_output)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 1149, in forward
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output_parallel = self.quant_method.apply(self,
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 142, in apply
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return F.linear(x, layer.weight, bias)
[1;36m(VllmWorkerProcess pid=2892662)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.00 MiB. GPU 5 has a total capacity of 31.74 GiB of which 173.12 MiB is free. Including non-PyTorch memory, this process has 31.56 GiB memory in use. Of the allocated memory 27.90 GiB is allocated by PyTorch, with 48.00 MiB allocated in private pools (e.g., CUDA Graphs), and 154.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop.
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Traceback (most recent call last):
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/utils.py", line 2196, in run_method
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 91, in start_worker_execution_loop
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.execute_model(execute_model_req=None)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 420, in execute_model
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.model_runner.execute_model(
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1724, in execute_model
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_or_intermediate_states = model_executable(
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 486, in forward
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/compilation/decorators.py", line 172, in __call__
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self.forward(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 348, in forward
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states, residual = layer(
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 247, in forward
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.self_attn(
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 180, in forward
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output, _ = self.o_proj(attn_output)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 1149, in forward
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output_parallel = self.quant_method.apply(self,
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 142, in apply
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return F.linear(x, layer.weight, bias)
[1;36m(VllmWorkerProcess pid=2892660)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.00 MiB. GPU 3 has a total capacity of 31.74 GiB of which 215.12 MiB is free. Including non-PyTorch memory, this process has 31.51 GiB memory in use. Of the allocated memory 27.90 GiB is allocated by PyTorch, with 48.00 MiB allocated in private pools (e.g., CUDA Graphs), and 154.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop.
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Traceback (most recent call last):
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/utils.py", line 2196, in run_method
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 91, in start_worker_execution_loop
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.execute_model(execute_model_req=None)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 420, in execute_model
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.model_runner.execute_model(
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1724, in execute_model
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_or_intermediate_states = model_executable(
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 486, in forward
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/compilation/decorators.py", line 172, in __call__
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self.forward(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 348, in forward
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states, residual = layer(
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 247, in forward
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.self_attn(
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 180, in forward
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output, _ = self.o_proj(attn_output)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 1149, in forward
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output_parallel = self.quant_method.apply(self,
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 142, in apply
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return F.linear(x, layer.weight, bias)
[1;36m(VllmWorkerProcess pid=2892661)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.00 MiB. GPU 4 has a total capacity of 31.74 GiB of which 221.12 MiB is free. Including non-PyTorch memory, this process has 31.51 GiB memory in use. Of the allocated memory 27.90 GiB is allocated by PyTorch, with 48.00 MiB allocated in private pools (e.g., CUDA Graphs), and 154.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop.
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Traceback (most recent call last):
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/utils.py", line 2196, in run_method
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 91, in start_worker_execution_loop
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.execute_model(execute_model_req=None)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 420, in execute_model
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.model_runner.execute_model(
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1724, in execute_model
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_or_intermediate_states = model_executable(
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 486, in forward
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/compilation/decorators.py", line 172, in __call__
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self.forward(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 348, in forward
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states, residual = layer(
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 247, in forward
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.self_attn(
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 180, in forward
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output, _ = self.o_proj(attn_output)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 1149, in forward
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output_parallel = self.quant_method.apply(self,
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 142, in apply
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return F.linear(x, layer.weight, bias)
[1;36m(VllmWorkerProcess pid=2892664)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.00 MiB. GPU 7 has a total capacity of 31.74 GiB of which 221.12 MiB is free. Including non-PyTorch memory, this process has 31.51 GiB memory in use. Of the allocated memory 27.90 GiB is allocated by PyTorch, with 48.00 MiB allocated in private pools (e.g., CUDA Graphs), and 154.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop.
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Traceback (most recent call last):
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/utils.py", line 2196, in run_method
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 91, in start_worker_execution_loop
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.execute_model(execute_model_req=None)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 420, in execute_model
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.model_runner.execute_model(
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1724, in execute_model
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_or_intermediate_states = model_executable(
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 486, in forward
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/compilation/decorators.py", line 172, in __call__
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self.forward(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 348, in forward
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states, residual = layer(
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 247, in forward
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.self_attn(
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 180, in forward
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output, _ = self.o_proj(attn_output)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 1149, in forward
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output_parallel = self.quant_method.apply(self,
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 142, in apply
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return F.linear(x, layer.weight, bias)
[1;36m(VllmWorkerProcess pid=2892659)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.00 MiB. GPU 2 has a total capacity of 31.74 GiB of which 167.12 MiB is free. Including non-PyTorch memory, this process has 31.56 GiB memory in use. Of the allocated memory 27.90 GiB is allocated by PyTorch, with 48.00 MiB allocated in private pools (e.g., CUDA Graphs), and 154.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Exception in worker VllmWorkerProcess while processing method start_worker_execution_loop.
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] Traceback (most recent call last):
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/executor/multiproc_worker_utils.py", line 236, in _run_worker_process
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = run_method(worker, method, args, kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/utils.py", line 2196, in run_method
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 91, in start_worker_execution_loop
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.execute_model(execute_model_req=None)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 420, in execute_model
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output = self.model_runner.execute_model(
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 1724, in execute_model
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_or_intermediate_states = model_executable(
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 486, in forward
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.model(input_ids, positions, kv_caches,
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/compilation/decorators.py", line 172, in __call__
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self.forward(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 348, in forward
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states, residual = layer(
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 247, in forward
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     hidden_states = self.self_attn(
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/models/qwen2.py", line 180, in forward
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output, _ = self.o_proj(attn_output)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 1149, in forward
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     output_parallel = self.quant_method.apply(self,
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]   File "/home/sqshou/anaconda3/envs/thm/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 142, in apply
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242]     return F.linear(x, layer.weight, bias)
[1;36m(VllmWorkerProcess pid=2892658)[0;0m ERROR 03-29 14:33:52 multiproc_worker_utils.py:242] torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 506.00 MiB. GPU 1 has a total capacity of 31.74 GiB of which 169.12 MiB is free. Including non-PyTorch memory, this process has 31.56 GiB memory in use. Of the allocated memory 27.90 GiB is allocated by PyTorch, with 48.00 MiB allocated in private pools (e.g., CUDA Graphs), and 154.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
ERROR 03-29 14:33:59 multiproc_worker_utils.py:124] Worker VllmWorkerProcess pid 2892663 died, exit code: -15
ERROR 03-29 14:33:59 multiproc_worker_utils.py:124] Worker VllmWorkerProcess pid 2892664 died, exit code: -15
INFO 03-29 14:33:59 multiproc_worker_utils.py:128] Killing local vLLM worker processes
tag_evol_tag5_7b_yxprompt
INFO 03-29 14:34:12 __init__.py:207] Automatically detected platform cuda.
WARNING 03-29 14:34:12 config.py:2448] Casting torch.bfloat16 to torch.float16.
